--1. product 테이블 생성
-- 1)
CREATE TABLE PRODUCT(
PRODUCT_NO NUMBER PRIMARY KEY,
PRODUCT_NAME VARCHAR2(20),
PRICE NUMBER,
STOCK NUMBER);
-- 2)
CREATE TABLE PRODUCT(
PRODUCT_NO NUMBER,
PRODUCT_NAME VARCHAR2(20),
PRICE NUMBER,
STOCK NUMBER,
PRIMARY KEY(PRODUCT_NO));
-- 3)
CREATE TABLE PRODUCT(
PRODUCT_NO NUMBER,
PRODUCT_NAME VARCHAR2(20),
PRICE NUMBER,
STOCK NUMBER,
CONSTRAINTS PRODUCT_PK PRIMARY KEY(PRODUCT_NO));

-- 2. orders 테이블 생성
-- 1)
CREATE TABLE ORDERS(
ORDER_NO NUMBER PRIMARY KEY,
ORDER_NAME VARCHAR2(20),
ORDER_PRODUCT NUMBER REFERENCES PRODUCT(PRODUCT_NO),
ORDER_DATE DATE);
-- 2)
CREATE TABLE ORDERS(
ORDER_NO NUMBER,
ORDER_NAME VARCHAR2(20),
ORDER_PRODUCT NUMBER,
ORDER_DATE DATE,
PRIMARY KEY(ORDER_NO),
FOREIGN KEY(ORDER_PRODUCT) REFERENCES PRODUCT(PRODUCT_NO));
-- 3)
CREATE TABLE ORDERS(
ORDER_NO NUMBER,
ORDER_NAME VARCHAR2(20),
ORDER_PRODUCT NUMBER,
ORDER_DATE DATE,
CONSTRAINTS ORDERS_PK PRIMARY KEY(ORDER_NO),
CONSTRAINTS PRODUCT_ORDERS_FK FOREIGN KEY(ORDER_PRODUCT) REFERENCES PRODUCT(PRODUCT_NO));

-- 3. product 테이블 삭제
DROP TABLE PRODUCT;

-- 4. orders 테이블 삭제
DROP TABLE ORDERS;

-- 5. 부모 - 자식 테이블 삭제 순서
-- 1) 자식 테이블 먼저 삭제
-- 2) 부모 테이블 나중에 삭제

-- 6. product 테이블 행(row, record) 추가
INSERT INTO PRODUCT(PRODUCT_NO, PRODUCT_NAME, PRICE, STOCK) VALUES (1, '새우깡', 1000, 15);
INSERT INTO PRODUCT VALUES(2, '감자깡', 1000, 10);

-- 7. orders 테이블 행(row, record) 추가
INSERT INTO ORDERS(ORDER_NO, ORDER_NAME, ORDER_PRODUCT, ORDER_DATE) VALUES(1000, 'ab***', 1, '21/03/03');
INSERT INTO ORDERS VALUES(1001, 'gt***', 4, '21/03/03');
