-- 테이블 목록 확인 (메타데이터 활용)
DESC TAB;  -- TAB 메타데이터
SELECT TNAME FROM TAB;
DESC USER_TABLES;  -- USER_TABLES 메타데이터
SELECT TABLE_NAME FROM USER_TABLES;

-- 제약조건 확인 (메타데이터 활용)
DESC USER_CONSTRAINTS;
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS;
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEE';
