-- 삭제순서 : 자식 먼저 삭제



-- 1:M 관계

DROP TABLE STUDENT;  -- 자식 삭제
DROP TABLE SCHOOL;   -- 부모 삭제

-- 학교 테이블
CREATE TABLE SCHOOL(
    SCHOOL_CODE     NUMBER,  -- PK
    SCHOOL_NAME     VARCHAR2(10 BYTE));

-- 학생 테이블
CREATE TABLE STUDENT(
    STUDENT_NO      NUMBER(5),  -- PK
    SCHOOL_CODE     NUMBER,  -- FK (관계 맺는 PK와 반드시 같은 타입)
    NAME            VARCHAR2(10 BYTE));

-- 제약조건(기본키, 외래키) 추가하기
ALTER TABLE SCHOOL ADD CONSTRAINT SCHOOL_PK PRIMARY KEY(SCHOOL_CODE);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_NO);
ALTER TABLE STUDENT ADD CONSTRAINT SCHOOL_STUDENT_FK FOREIGN KEY(SCHOOL_CODE) REFERENCES SCHOOL(SCHOOL_CODE);


-- DDL : Data Definition Language
-- 데이터 정의어
-- 1. CREATE문 : 데이터베이스 객체 생성
-- 2. DROP문   : 데이터베이스 객체 삭제
-- 3. ALTER문  : 데이터베이스 객체 수정


-- M:N 관계
-- 학생(M) : 과목(N)     -> 테이블 2개는 물리적 구현 불가
-- 학생 - 수강신청 - 과목 : 테이블 3개로 구현 가능

DROP TABLE ENROLL;  -- 자식
DROP TABLE SUBJECT; -- 부모
DROP TABLE STUDENT; -- 부모


-- 학생 테이블
CREATE TABLE STUDENT(
    STUDENT_NO  NUMBER(5),
    NAME        VARCHAR2(10 BYTE),
    AGE         NUMBER(3));

-- 과목 테이블
CREATE TABLE SUBJECT(
    SUBJECT_CODE    CHAR(1 BYTE),
    SUBJECT_NAME    VARCHAR2(10 BYTE),
    PROFESSOR       VARCHAR2(10 BYTE));

-- 수강신청 테이블
CREATE TABLE ENROLL(
    ENROLL_NO       NUMBER,
    STUDENT_NO      NUMBER(5),      -- FK
    SUBJECT_CODE    CHAR(1 BYTE));  -- FK


-- 제약조건 추가
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_NO);
ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_PK PRIMARY KEY(SUBJECT_CODE);
ALTER TABLE ENROLL ADD CONSTRAINT ENROLL_PK PRIMARY KEY(ENROLL_NO);
ALTER TABLE ENROLL ADD CONSTRAINT STUDENT_ENROLL_FK FOREIGN KEY(STUDENT_NO) REFERENCES STUDENT(STUDENT_NO);
ALTER TABLE ENROLL ADD CONSTRAINT SUBJECT_ENROLL_FK FOREIGN KEY(SUBJECT_CODE) REFERENCES SUBJECT(SUBJECT_CODE);
