CREATE TABLE CONTACT
( 
    NO           NUMBER PRIMARY KEY,
    NAME         VARCHAR2(100),
    TEL          VARCHAR2(100),
    ADDRESS      VARCHAR2(100),
    BIRTHDAY     VARCHAR2(10)
);

CREATE SEQUENCE CONTACT_SEQ NOCACHE;

CREATE TABLE NOTICE;
(
    NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(100),
    CREATED DATE,
    LASTMODIFIED DATE
);

CREATE SEQUENCE  NOTICE_SEQ NOCACHE;