DROP TABLE BOARD;
CREATE TABLE BOARD(

	BNO			VARCHAR2(5) PRIMARY KEY,
	WRITER		VARCHAR2(10),
	CONTENT		VARCHAR2(50) NOT NULL,
	BDATE		DATE
);


INSERT INTO BOARD VALUES('10000', 'ALICE', '만나서 반갑습니다.', '2021-11-15');
INSERT INTO BOARD VALUES('10001', 'ALIEN', '나도 반갑습니다.', SYSDATE);
COMMIT

