DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
    MEMBER_NO NUMBER PRIMARY KEY,
    ID VARCHAR2(100) NOT NULL UNIQUE,
    NAME VARCHAR2(100),
    GENDER VARCHAR2(2),
    ADDRESS VARCHAR2(100)
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD
(
    BOARD_NO NUMBER PRIMARY KEY,
    TITLE   VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(100),
    WRITER VARCHAR2(100),
    IP  VARCHAR2(40),
    CREATED DATE,
    LASTMODIFIED DATE
);

CREATE TABLE BOARD_ATTACH
(
    UUID VARCHAR2(32) PRIMARY KEY,   -- 저장된 첨부파일명을 의미함  = SAVED
    PATH    VARCHAR2(300),
    ORIGIN VARCHAR2(300),
    FILETYPE VARCHAR2(1) DEFAULT 'I',       -- 이미지가 'I'
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO)  
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;